title: Sphagnum Field Guide
description: A comprehensive guide to Sphagnum species
baseurl: "/Sphagnum-Field-Guide"
url: "https://danielesolbakk.github.io"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  parse_block_html: true
  parse_span_html: true
  syntax_highlighter_opts:
    disable: true
theme: minima
permalink: pretty

# Include all directories in the build
include:
  - "Subgenus Acutifolia"
  - "Subgenus Cuspidata"
  - "Subgenus Rigida"
  - "Subgenus Sphagnum"
  - "Subgenus Subsecunda"

# Plugins
plugins:
  - jekyll-feed
